[env:esp32dev]
platform = espressif32 @ 7.1.2
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions_custom.csv

lib_deps = 
    https://github.com/tzapu/WiFiManager.git#v2.0.17
    bblanchon/ArduinoJson @ ^6.21.3
    z3t0/IRremote @ 4.7.1
